### ISSUE TITLE
Box Edit versions 3.3.1 and 3.3.2 don't work when installed via Munki

### ISSUE THREAD

**Issue by escapecorp** [joshua-d-miller/recipe-overrides#1]
Our end users noted that after Box Edit 3.3.1 (early May) and 3.3.2 (mid-May) arrived, the product ceased to work when installed via the munki recipe. I suspect it has to do with the addition of the Box Device Trust application that is new in 3.3.1 and later.

**Comment by joshua-d-miller** [comment]
Hello,

Thanks for letting me know about Box Edit's new change. I have updated my recipe as well as my override however I would suggest creating your own overrides. These are just for our backup and are configured for our specific environment.

Thanks! 👍
